Update dirhunter

diff --git a/dirhunter b/dirhunter
--- a/dirhunter
+++ b/dirhunter
@@ -14,18 +14,15 @@ SITE=$1
 ACCEPTED="200 403"
 AGENTS=useragents
 DEFAULT=wordlists/common.txt
-IP=`echo $SITE | awk -F[/:] '{print $4}'`
+IP=`awk -F[/:] '{print $4}' <<< "$SITE"`
 
 info(){
-
 	echo -e "\x1B[34m[*]\x1B[0m Start time: \x1B[1;37m`date "+%F %X"`\x1B[0m" 									#Start time
 	echo -e "\x1B[34m[*]\x1B[0m Hunting subdirectories: \x1B[1;37m$SITE\x1B[0m \x1B[34m[`dig +short $IP @resolver1.opendns.com | tail -1`]\x1B[0m"	#Website info
 	echo -e "\x1B[34m[*]\x1B[0m Wordlist file: \x1B[1;37m$WD\x1B[0m \x1B[34m[`wc -l < $WD` lines]\x1B[0m\n"						#Wordlist info
-
 }
 
 check(){
-
 	echo $ACCEPTED | grep -o -q $STATUS     		      #Checking whether the status code matches the $ACCEPTED variable
         if [ $? -eq 0 ]; then
 		echo -e "\x1B[32m[+] \x1B[32m[$STATUS]\x1B[0m $SITE$word"
@@ -37,32 +34,26 @@ check(){
                 NEWURL=`echo $LOCATION | sed 's/^.*: //'`             #Grep the URL in "Location" header
                 echo -e "\x1B[33m[*]\x1B[0m \x1B[33m[$STATUS]\x1B[0m \x1B[1;37m$SITE$word\x1B[0m redirects to: \x1B[1;37m$NEWURL\x1B[0m"
 	fi
-
 }
 
 while :; do
-
-	if [ -z $SITE ]; then
+	if [ -z "$SITE" ]; then
 		echo -e "\x1B[34m[*]\x1B[0m \x1B[1;37mUsage: dirhunter <URL_Base> [<Wordlist_File>] [Options]\x1B[0m"
 		echo -e "\x1B[34m[*]\x1B[0m Dirhunter is a Web Content Scanner. It searches for (existing/hidden) subdirectories on web servers, inspecting the HTTP response status codes.\n\n  -a, --agent           Customize your User-Agent.\n  -v, --verbose         Show also 404 [Not Found] pages.\n  -w, --wordlist        Specify your own wordlist.\n"
 		break
 
-	else	
-		echo $SITE | egrep -q '^(http|https)://'  #Regex HTTP/HTTPS
-		if [ $? -eq "1" ]; then
-			echo -e "\x1B[31m[-]\x1B[0m Invalid URL format: \x1B[1;37m$SITE\x1B[0m\n\x1B[31m[-]\x1B[0m Use: “http://host/” or “https://host/”\x1B[0m\n\x1B[31m[-]\x1B[0m Exiting..."
-			break
-	        else
-        	        echo $SITE | grep -q -E '/'$      #Force an ending "/" on URLs
-                	if [ $? -eq 1 ]; then
-                        	SITE="$SITE/"
-	                fi
-        	fi
+	else
+		if egrep -q '^(http|https)://' <<< "$SITE"; then
+			if ! grep -qE '/'$ <<< "$SITE"; then
+				SITE="$SITE/"
+			fi
+		else
+			echo -e "\x1B[31m[-]\x1B[0m Invalid URL format: \x1B[1;37m$SITE\x1B[0m\n\x1B[31m[-]\x1B[0m Use: “http://host/” or “https://host/”\x1B[0m\n\x1B[31m[-]\x1B[0m Exiting..." && break
+		fi
 	fi
 
 	case $2 in
 	--wordlist|-w)
-
 		if [ -z $3 ]; then
 			echo -e "\x1B[31m[-]\x1B[0m Missing operand.\x1B[0m\n\x1B[31m[-]\x1B[0m Exiting..."
                        	break
@@ -79,14 +70,11 @@ while :; do
 			break
 		fi
 		shift
-
 	;;
 	--agent|-a)
-
 		if [ -z "$3" ]; then
                         echo -e "\x1B[31m[-]\x1B[0m Missing operand.\x1B[0m\n\x1B[31m[-]\x1B[0m Exiting..."
                         break
-
 		else
 			cat $AGENTS | grep -o -q "$3"$
 			if [ $? -eq 0 ]; then
@@ -102,7 +90,6 @@ while :; do
 			fi
 		fi
 		shift
-
 	;;
 	--verbose|-v)
 
@@ -125,10 +112,8 @@ while :; do
         		fi
 		done
 		shift	
-
 	;;
         '')
-
 		if [ -z $2 ] && [ -f $DEFAULT ]; then
 			WD=$DEFAULT
 			info
@@ -141,14 +126,11 @@ while :; do
         		break
 		fi
 		shift
-
 	;;
 	*)
 
 		echo -e "\x1B[31m[-]\x1B[0m Invalid option.\n\x1B[31m[-]\x1B[0m Exiting..." 		
 		break
-
 	esac
 	shift
-
 done
